-- Insertar proyectos de ejemplo para probar el sistema de filtros

-- Primero, asegurémonos de que hay categorías
INSERT INTO project_categories (id, name, display_name, description, icon, color, is_active, sort_order, created_at)
VALUES 
  ('tech-1', 'technology', 'Tecnología', 'Proyectos relacionados con tecnología', 'laptop', '#3B82F6', true, 1, NOW()),
  ('health-1', 'healthcare', 'Salud', 'Proyectos de salud y medicina', 'heart', '#10B981', true, 2, NOW()),
  ('fintech-1', 'fintech', 'FinTech', 'Proyectos de tecnología financiera', 'dollar-sign', '#F59E0B', true, 3, NOW()),
  ('ecommerce-1', 'ecommerce', 'E-commerce', 'Proyectos de comercio electrónico', 'shopping-cart', '#EF4444', true, 4, NOW()),
  ('education-1', 'education', 'Educación', 'Proyectos educativos', 'book', '#8B5CF6', true, 5, NOW())
ON CONFLICT (id) DO NOTHING;

-- Insertar proyectos de ejemplo
INSERT INTO projects (
  id,
  creator_id,
  title,
  tagline,
  description,
  detailed_description,
  status,
  visibility,
  is_featured,
  is_verified,
  category,
  industry,
  stage,
  start_date,
  target_completion_date,
  logo_url,
  cover_image_url,
  demo_url,
  website_url,
  repository_url,
  tech_stack,
  required_skills,
  funding_goal,
  funding_raised,
  funding_stage,
  equity_offered,
  view_count,
  like_count,
  bookmark_count,
  application_count,
  team_size_current,
  team_size_target,
  is_seeking_cofounder,
  is_seeking_investors,
  is_seeking_mentors,
  is_open_to_collaboration,
  accepts_applications,
  auto_accept_applications,
  requires_application_message,
  tags,
  created_at,
  updated_at,
  published_at,
  last_activity_at
) VALUES 
(
  'proj-001',
  '3ba6c41a-1f33-4832-97e4-774e523fe001',
  'EcoTracker - App de Sostenibilidad',
  'Rastrea tu huella de carbono y vive más verde',
  'Una aplicación móvil que ayuda a los usuarios a rastrear su huella de carbono diaria y les proporciona consejos personalizados para reducir su impacto ambiental.',
  'EcoTracker es una aplicación integral que combina gamificación con datos científicos para hacer que la vida sostenible sea accesible y divertida. Los usuarios pueden rastrear sus actividades diarias, desde el transporte hasta el consumo de alimentos, y recibir retroalimentación instantánea sobre su impacto ambiental.',
  'active',
  'public',
  true,
  false,
  'technology',
  'Technology',
  'mvp',
  '2024-01-15',
  '2024-12-31',
  null,
  null,
  'https://demo.ecotracker.app',
  null,
  'https://github.com/ecotracker/app',
  '{"React Native", "Node.js", "MongoDB", "Express"}',
  '{"Mobile Development", "UI/UX Design", "Data Science", "Marketing"}',
  50000,
  15000,
  'seed',
  10,
  156,
  23,
  8,
  12,
  2,
  5,
  true,
  true,
  false,
  true,
  true,
  false,
  true,
  '{"sostenibilidad", "medio ambiente", "móvil", "gamificación"}',
  '2024-01-15 10:00:00',
  '2024-08-14 15:30:00',
  '2024-01-15 10:00:00',
  '2024-08-14 15:30:00'
),
(
  'proj-002',
  '3ba6c41a-1f33-4832-97e4-774e523fe001',
  'MediConnect - Telemedicina',
  'Conecta pacientes con doctores al instante',
  'Plataforma de telemedicina que permite consultas médicas virtuales seguras, con integración de expedientes médicos digitales y sistema de citas inteligente.',
  'MediConnect revoluciona el acceso a la atención médica mediante videoconsultas HD, diagnósticos asistidos por IA, y un sistema completo de gestión de expedientes médicos. Incluye funcionalidades de farmacia digital y seguimiento post-consulta.',
  'active',
  'public',
  false,
  true,
  'healthcare',
  'Healthcare',
  'beta',
  '2023-06-01',
  '2024-10-15',
  null,
  null,
  null,
  'https://mediconnect.health',
  null,
  '{"Next.js", "TypeScript", "PostgreSQL", "WebRTC"}',
  '{"Full Stack Development", "Healthcare IT", "DevOps", "Product Management"}',
  100000,
  45000,
  'series_a',
  15,
  234,
  45,
  12,
  18,
  4,
  8,
  false,
  true,
  true,
  true,
  true,
  false,
  true,
  '{"salud", "telemedicina", "IA", "Madrid"}',
  '2023-06-01 09:15:00',
  '2024-08-14 11:20:00',
  '2023-06-01 09:15:00',
  '2024-08-14 11:20:00'
),
(
  'proj-003',
  '3ba6c41a-1f33-4832-97e4-774e523fe001',
  'CryptoWallet Pro',
  'Wallet multicriptomoneda con DeFi integrado',
  'Wallet digital avanzado que soporta múltiples criptomonedas con funciones DeFi integradas, staking automático y análisis de portafolio.',
  'CryptoWallet Pro es más que un wallet tradicional. Incluye herramientas avanzadas de trading, análisis técnico, yield farming automatizado, y una interfaz intuitiva que hace las finanzas descentralizadas accesibles para todos.',
  'active',
  'public',
  true,
  false,
  'fintech',
  'Finance',
  'launch',
  '2023-09-01',
  '2024-06-30',
  null,
  null,
  'https://demo.cryptowallet.pro',
  'https://cryptowallet.pro',
  'https://github.com/cryptowallet/core',
  '{"React", "Ethereum", "Web3", "Rust"}',
  '{"Blockchain Development", "Smart Contracts", "Security", "Mobile Development"}',
  200000,
  80000,
  'series_a',
  8,
  412,
  67,
  19,
  25,
  3,
  6,
  true,
  false,
  false,
  true,
  true,
  false,
  true,
  '{"blockchain", "DeFi", "cripto", "Barcelona"}',
  '2023-09-01 14:30:00',
  '2024-08-14 16:45:00',
  '2023-09-01 14:30:00',
  '2024-08-14 16:45:00'
),
(
  'proj-004',
  '3ba6c41a-1f33-4832-97e4-774e523fe001',
  'EduFlow - Plataforma Educativa',
  'Aprendizaje personalizado con IA',
  'Plataforma de e-learning que utiliza inteligencia artificial para personalizar el contenido educativo según el estilo y ritmo de aprendizaje de cada estudiante.',
  'EduFlow transforma la educación online mediante algoritmos de IA que adaptan el contenido, la dificultad y el método de enseñanza a cada estudiante individual. Incluye gamificación, realidad virtual y análisis predictivo del rendimiento académico.',
  'active',
  'public',
  false,
  false,
  'education',
  'Education',
  'idea',
  '2024-03-01',
  '2025-02-28',
  null,
  null,
  null,
  null,
  null,
  '{"Python", "TensorFlow", "React", "Django"}',
  '{"AI/ML", "Frontend Development", "Educational Design", "Data Science"}',
  75000,
  0,
  'pre_seed',
  12,
  89,
  15,
  6,
  8,
  1,
  4,
  true,
  true,
  true,
  true,
  true,
  false,
  true,
  '{"educación", "IA", "e-learning", "remoto"}',
  '2024-03-01 08:45:00',
  '2024-08-14 12:15:00',
  '2024-03-01 08:45:00',
  '2024-08-14 12:15:00'
),
(
  'proj-005',
  '3ba6c41a-1f33-4832-97e4-774e523fe001',
  'LocalMarket - Marketplace Local',
  'Conecta negocios locales con clientes',
  'Marketplace que conecta pequeños negocios locales con clientes de su área, ofreciendo delivery rápido y promoción de la economía local.',
  'LocalMarket es una plataforma que fortalece las comunidades locales conectando negocios de barrio con residentes cercanos. Incluye sistema de delivery propio, programa de fidelización y herramientas de marketing digital para pequeños comercios.',
  'active',
  'public',
  false,
  false,
  'ecommerce',
  'E-commerce',
  'growth',
  '2023-11-01',
  '2024-08-31',
  null,
  null,
  'https://demo.localmarket.es',
  'https://localmarket.es',
  null,
  '{"Vue.js", "Laravel", "MySQL", "Stripe"}',
  '{"E-commerce Development", "Mobile Apps", "Logistics", "Community Management"}',
  120000,
  60000,
  'seed',
  5,
  298,
  38,
  14,
  22,
  6,
  12,
  false,
  false,
  false,
  true,
  true,
  true,
  false,
  '{"marketplace", "local", "delivery", "Valencia"}',
  '2023-11-01 11:00:00',
  '2024-08-14 14:25:00',
  '2023-11-01 11:00:00',
  '2024-08-14 14:25:00'
);

-- Actualizar estadísticas de actividad reciente
UPDATE projects SET last_activity_at = NOW() - INTERVAL '1 day' WHERE id = 'proj-001';
UPDATE projects SET last_activity_at = NOW() - INTERVAL '3 hours' WHERE id = 'proj-002';
UPDATE projects SET last_activity_at = NOW() - INTERVAL '2 days' WHERE id = 'proj-003';
UPDATE projects SET last_activity_at = NOW() - INTERVAL '1 week' WHERE id = 'proj-004';
UPDATE projects SET last_activity_at = NOW() - INTERVAL '5 hours' WHERE id = 'proj-005';
