-- Sample projects data for testing search functionality
-- Run this in your Supabase SQL editor to add test projects

INSERT INTO projects (
  creator_id,
  title,
  tagline,
  description,
  category,
  industry,
  stage,
  status,
  visibility,
  funding_stage,
  team_size_current,
  team_size_target,
  is_seeking_cofounder,
  is_seeking_investors,
  is_seeking_mentors,
  tags,
  view_count,
  like_count,
  application_count,
  created_at,
  updated_at
) VALUES
-- Proyecto 1: FinTech
(
  'a1089270-efec-4c4b-a97f-22bb0cd2f313',
  'PayFlow - Pagos Instantáneos',
  'La próxima generación de pagos digitales para pequeñas empresas',
  'PayFlow es una plataforma de pagos que permite a pequeñas empresas procesar pagos instantáneos con tarifas mínimas. Utilizamos tecnología blockchain para garantizar transacciones seguras y rápidas.',
  'fintech',
  'fintech',
  'mvp',
  'active',
  'public',
  'pre_seed',
  2,
  5,
  true,
  true,
  false,
  ARRAY['fintech', 'pagos', 'blockchain', 'startup', 'madrid'],
  45,
  12,
  8,
  NOW() - INTERVAL '2 days',
  NOW()
),

-- Proyecto 2: HealthTech
(
  'a1089270-efec-4c4b-a97f-22bb0cd2f313',
  'MediConnect - Telemedicina',
  'Conectando pacientes con doctores especializados',
  'MediConnect facilita la conexión entre pacientes y doctores especialistas a través de videoconsultas seguras. Nuestra IA ayuda a pre-diagnosticar síntomas y recomendar el especialista adecuado.',
  'healthtech',
  'healthtech',
  'growth',
  'active',
  'public',
  'seed',
  5,
  7,
  true,
  false,
  true,
  ARRAY['salud', 'telemedicina', 'ia', 'doctores', 'barcelona'],
  78,
  23,
  15,
  NOW() - INTERVAL '5 days',
  NOW()
),

-- Proyecto 3: EdTech
(
  'a1089270-efec-4c4b-a97f-22bb0cd2f313',
  'LearnAI - Educación Personalizada',
  'IA que adapta el aprendizaje a cada estudiante',
  'LearnAI utiliza inteligencia artificial para crear planes de estudio personalizados. Nuestro algoritmo analiza el estilo de aprendizaje de cada estudiante y adapta el contenido en tiempo real.',
  'edtech',
  'edtech',
  'beta',
  'active',
  'public',
  'pre_seed',
  3,
  5,
  true,
  true,
  true,
  ARRAY['educacion', 'ia', 'aprendizaje', 'estudiantes', 'valencia'],
  156,
  34,
  22,
  NOW() - INTERVAL '1 week',
  NOW()
),

-- Proyecto 4: E-commerce
(
  'a1089270-efec-4c4b-a97f-22bb0cd2f313',
  'EcoShop - Marketplace Sostenible',
  'El marketplace para productos ecológicos y sostenibles',
  'EcoShop es un marketplace dedicado exclusivamente a productos ecológicos y sostenibles. Conectamos consumidores conscientes con marcas que priorizan la sostenibilidad ambiental.',
  'ecommerce',
  'sustainability',
  'launch',
  'active',
  'public',
  'series_a',
  8,
  12,
  false,
  true,
  false,
  ARRAY['ecommerce', 'sostenibilidad', 'ecologico', 'marketplace', 'sevilla'],
  89,
  18,
  12,
  NOW() - INTERVAL '3 days',
  NOW()
),

-- Proyecto 5: SaaS
(
  'a1089270-efec-4c4b-a97f-22bb0cd2f313',
  'TaskMaster - Gestión de Proyectos',
  'La herramienta de gestión de proyectos que tu equipo necesita',
  'TaskMaster simplifica la gestión de proyectos con una interfaz intuitiva y características avanzadas de colaboración. Ideal para equipos remotos y startups en crecimiento.',
  'saas',
  'productivity',
  'growth',
  'active',
  'public',
  'seed',
  6,
  9,
  true,
  false,
  true,
  ARRAY['saas', 'productividad', 'gestion', 'equipos', 'bilbao'],
  203,
  41,
  28,
  NOW() - INTERVAL '4 days',
  NOW()
);
